//  Felix-Bang：FBRotate
//　　 へ　　　　　／|
//　　/＼7　　　 ∠＿/
//　 /　│　　 ／　／
//　│　Z ＿,＜　／　　 /`ヽ
//　│　　　　　ヽ　　 /　　〉
//　 Y　　　　　`　 /　　/
//　ｲ●　､　●　　⊂⊃〈　　/
//　()　 へ　　　　|　＼〈
//　　>ｰ ､_　 ィ　 │ ／／
//　 / へ　　 /　ﾉ＜| ＼＼
//　 ヽ_ﾉ　　(_／　 │／／
//　　7　　　　　　　|／
//　　＞―r￣￣`ｰ―＿
// Describe：旋转
// Createtime：2018/10/09


using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace Felix
{
	public class FBRotate : MonoBehaviour
	{
		public float Speed = 360;

		void Update ()
		{
            transform.Rotate(Vector3.forward, Time.deltaTime * Speed, Space.Self);
		}
	}
}

